#!/usr/bin/env bash

declare -a BPM_CRATE_1_FPGA
declare -a BPM_CRATE_2_FPGA
declare -a BPM_CRATE_3_FPGA
declare -a BPM_CRATE_4_FPGA
declare -a BPM_CRATE_5_FPGA
declare -a BPM_CRATE_6_FPGA
declare -a BPM_CRATE_7_FPGA
declare -a BPM_CRATE_8_FPGA
declare -a BPM_CRATE_9_FPGA
declare -a BPM_CRATE_10_FPGA
declare -a BPM_CRATE_11_FPGA
declare -a BPM_CRATE_12_FPGA
declare -a BPM_CRATE_13_FPGA
declare -a BPM_CRATE_14_FPGA
declare -a BPM_CRATE_15_FPGA
declare -a BPM_CRATE_16_FPGA
declare -a BPM_CRATE_17_FPGA
declare -a BPM_CRATE_18_FPGA
declare -a BPM_CRATE_19_FPGA
declare -a BPM_CRATE_20_FPGA
declare -a BPM_CRATE_21_FPGA
declare -a BPM_CRATE_22_FPGA
declare -a BPM_CRATE_23_FPGA
declare -a BPM_CRATE_24_FPGA
declare -a BPM_CRATE_25_FPGA

# Crate 1 FPGA bitstreams definitions
BPM_CRATE_1_FPGA[1]="timing"
BPM_CRATE_1_FPGA[2]="fofb"
BPM_CRATE_1_FPGA[3]=""
BPM_CRATE_1_FPGA[4]=""
BPM_CRATE_1_FPGA[5]=""
BPM_CRATE_1_FPGA[6]=""
BPM_CRATE_1_FPGA[7]="sr"
BPM_CRATE_1_FPGA[8]="sr"
BPM_CRATE_1_FPGA[9]="sr"
BPM_CRATE_1_FPGA[10]="sr"
BPM_CRATE_1_FPGA[11]="bo"
BPM_CRATE_1_FPGA[12]=""

BPM_CRATE_1_CPU_HOSTNAME="IA-01RaBPM-CO-IOCSrv"
BPM_CRATE_1_MCH_HOSTNAME="IA-01RaBPM-CO-CrateCtrl"

# Crate 2 FPGA bitstreams definitions
BPM_CRATE_2_FPGA[1]="timing"
BPM_CRATE_2_FPGA[2]="fofb"
BPM_CRATE_2_FPGA[3]=""
BPM_CRATE_2_FPGA[4]=""
BPM_CRATE_2_FPGA[5]=""
BPM_CRATE_2_FPGA[6]=""
BPM_CRATE_2_FPGA[7]="sr"
BPM_CRATE_2_FPGA[8]="sr"
BPM_CRATE_2_FPGA[9]="sr"
BPM_CRATE_2_FPGA[10]="sr"
BPM_CRATE_2_FPGA[11]="bo"
BPM_CRATE_2_FPGA[12]="bo"

BPM_CRATE_2_CPU_HOSTNAME="IA-02RaBPM-CO-IOCSrv"
BPM_CRATE_2_MCH_HOSTNAME="IA-02RaBPM-CO-CrateCtrl"

# Crate 3 FPGA bitstreams definitions
BPM_CRATE_3_FPGA[1]="timing"
BPM_CRATE_3_FPGA[2]="fofb"
BPM_CRATE_3_FPGA[3]=""
BPM_CRATE_3_FPGA[4]=""
BPM_CRATE_3_FPGA[5]=""
BPM_CRATE_3_FPGA[6]=""
BPM_CRATE_3_FPGA[7]="sr"
BPM_CRATE_3_FPGA[8]="sr"
BPM_CRATE_3_FPGA[9]="sr"
BPM_CRATE_3_FPGA[10]="sr"
BPM_CRATE_3_FPGA[11]="bo"
BPM_CRATE_3_FPGA[12]=""

BPM_CRATE_3_CPU_HOSTNAME="IA-03RaBPM-CO-IOCSrv"
BPM_CRATE_3_MCH_HOSTNAME="IA-03RaBPM-CO-CrateCtrl"

# Crate 4 FPGA bitstreams definitions
BPM_CRATE_4_FPGA[1]="timing"
BPM_CRATE_4_FPGA[2]="fofb"
BPM_CRATE_4_FPGA[3]=""
BPM_CRATE_4_FPGA[4]=""
BPM_CRATE_4_FPGA[5]=""
BPM_CRATE_4_FPGA[6]=""
BPM_CRATE_4_FPGA[7]="sr"
BPM_CRATE_4_FPGA[8]="sr"
BPM_CRATE_4_FPGA[9]="sr"
BPM_CRATE_4_FPGA[10]="sr"
BPM_CRATE_4_FPGA[11]="bo"
BPM_CRATE_4_FPGA[12]="bo"

BPM_CRATE_4_CPU_HOSTNAME="IA-04RaBPM-CO-IOCSrv"
BPM_CRATE_4_MCH_HOSTNAME="IA-04RaBPM-CO-CrateCtrl"

# Crate 5 FPGA bitstreams definitions
BPM_CRATE_5_FPGA[1]="timing"
BPM_CRATE_5_FPGA[2]="fofb"
BPM_CRATE_5_FPGA[3]=""
BPM_CRATE_5_FPGA[4]=""
BPM_CRATE_5_FPGA[5]=""
BPM_CRATE_5_FPGA[6]=""
BPM_CRATE_5_FPGA[7]="sr"
BPM_CRATE_5_FPGA[8]="sr"
BPM_CRATE_5_FPGA[9]="sr"
BPM_CRATE_5_FPGA[10]="sr"
BPM_CRATE_5_FPGA[11]="bo"
BPM_CRATE_5_FPGA[12]=""

BPM_CRATE_5_CPU_HOSTNAME="IA-05RaBPM-CO-IOCSrv"
BPM_CRATE_5_MCH_HOSTNAME="IA-05RaBPM-CO-CrateCtrl"

# Crate 6 FPGA bitstreams definitions
BPM_CRATE_6_FPGA[1]="timing"
BPM_CRATE_6_FPGA[2]="fofb"
BPM_CRATE_6_FPGA[3]=""
BPM_CRATE_6_FPGA[4]="pbpm"
BPM_CRATE_6_FPGA[5]=""
BPM_CRATE_6_FPGA[6]="sr"
BPM_CRATE_6_FPGA[7]="sr"
BPM_CRATE_6_FPGA[8]="sr"
BPM_CRATE_6_FPGA[9]="sr"
BPM_CRATE_6_FPGA[10]="sr"
BPM_CRATE_6_FPGA[11]="bo"
BPM_CRATE_6_FPGA[12]="bo"

BPM_CRATE_6_CPU_HOSTNAME="IA-06RaBPM-CO-IOCSrv"
BPM_CRATE_6_MCH_HOSTNAME="IA-06RaBPM-CO-CrateCtrl"

# Crate 7 FPGA bitstreams definitions
BPM_CRATE_7_FPGA[1]="timing"
BPM_CRATE_7_FPGA[2]="fofb"
BPM_CRATE_7_FPGA[3]=""
BPM_CRATE_7_FPGA[4]="pbpm"
BPM_CRATE_7_FPGA[5]=""
BPM_CRATE_7_FPGA[6]="sr"
BPM_CRATE_7_FPGA[7]="sr"
BPM_CRATE_7_FPGA[8]="sr"
BPM_CRATE_7_FPGA[9]="sr"
BPM_CRATE_7_FPGA[10]="sr"
BPM_CRATE_7_FPGA[11]="bo"
BPM_CRATE_7_FPGA[12]=""

BPM_CRATE_7_CPU_HOSTNAME="IA-07RaBPM-CO-IOCSrv"
BPM_CRATE_7_MCH_HOSTNAME="IA-07RaBPM-CO-CrateCtrl"

# Crate 8 FPGA bitstreams definitions
BPM_CRATE_8_FPGA[1]="timing"
BPM_CRATE_8_FPGA[2]="fofb"
BPM_CRATE_8_FPGA[3]=""
BPM_CRATE_8_FPGA[4]="pbpm"
BPM_CRATE_8_FPGA[5]=""
BPM_CRATE_8_FPGA[6]="sr"
BPM_CRATE_8_FPGA[7]="sr"
BPM_CRATE_8_FPGA[8]="sr"
BPM_CRATE_8_FPGA[9]="sr"
BPM_CRATE_8_FPGA[10]="sr"
BPM_CRATE_8_FPGA[11]="bo"
BPM_CRATE_8_FPGA[12]="bo"

BPM_CRATE_8_CPU_HOSTNAME="IA-08RaBPM-CO-IOCSrv"
BPM_CRATE_8_MCH_HOSTNAME="IA-08RaBPM-CO-CrateCtrl"

# Crate 9 FPGA bitstreams definitions
BPM_CRATE_9_FPGA[1]="timing"
BPM_CRATE_9_FPGA[2]="fofb"
BPM_CRATE_9_FPGA[3]=""
BPM_CRATE_9_FPGA[4]="pbpm"
BPM_CRATE_9_FPGA[5]=""
BPM_CRATE_9_FPGA[6]="sr"
BPM_CRATE_9_FPGA[7]="sr"
BPM_CRATE_9_FPGA[8]="sr"
BPM_CRATE_9_FPGA[9]="sr"
BPM_CRATE_9_FPGA[10]="sr"
BPM_CRATE_9_FPGA[11]="bo"
BPM_CRATE_9_FPGA[12]=""

BPM_CRATE_9_CPU_HOSTNAME="IA-09RaBPM-CO-IOCSrv"
BPM_CRATE_9_MCH_HOSTNAME="IA-09RaBPM-CO-CrateCtrl"

# Crate 10 FPGA bitstreams definitions
BPM_CRATE_10_FPGA[1]="timing"
BPM_CRATE_10_FPGA[2]="fofb"
BPM_CRATE_10_FPGA[3]=""
BPM_CRATE_10_FPGA[4]="pbpm"
BPM_CRATE_10_FPGA[5]="pbpm"
BPM_CRATE_10_FPGA[6]="sr"
BPM_CRATE_10_FPGA[7]="sr"
BPM_CRATE_10_FPGA[8]="sr"
BPM_CRATE_10_FPGA[9]="sr"
BPM_CRATE_10_FPGA[10]="sr"
BPM_CRATE_10_FPGA[11]="bo"
BPM_CRATE_10_FPGA[12]="bo"

BPM_CRATE_10_CPU_HOSTNAME="IA-10RaBPM-CO-IOCSrv"
BPM_CRATE_10_MCH_HOSTNAME="IA-10RaBPM-CO-CrateCtrl"

# Crate 11 FPGA bitstreams definitions
BPM_CRATE_11_FPGA[1]="timing"
BPM_CRATE_11_FPGA[2]="fofb"
BPM_CRATE_11_FPGA[3]=""
BPM_CRATE_11_FPGA[4]="pbpm"
BPM_CRATE_11_FPGA[5]=""
BPM_CRATE_11_FPGA[6]="sr"
BPM_CRATE_11_FPGA[7]="sr"
BPM_CRATE_11_FPGA[8]="sr"
BPM_CRATE_11_FPGA[9]="sr"
BPM_CRATE_11_FPGA[10]="sr"
BPM_CRATE_11_FPGA[11]="bo"
BPM_CRATE_11_FPGA[12]=""

BPM_CRATE_11_CPU_HOSTNAME="IA-11RaBPM-CO-IOCSrv"
BPM_CRATE_11_MCH_HOSTNAME="IA-11RaBPM-CO-CrateCtrl"

# Crate 12 FPGA bitstreams definitions
BPM_CRATE_12_FPGA[1]="timing"
BPM_CRATE_12_FPGA[2]="fofb"
BPM_CRATE_12_FPGA[3]=""
BPM_CRATE_12_FPGA[4]="pbpm"
BPM_CRATE_12_FPGA[5]=""
BPM_CRATE_12_FPGA[6]="sr"
BPM_CRATE_12_FPGA[7]="sr"
BPM_CRATE_12_FPGA[8]="sr"
BPM_CRATE_12_FPGA[9]="sr"
BPM_CRATE_12_FPGA[10]="sr"
BPM_CRATE_12_FPGA[11]="bo"
BPM_CRATE_12_FPGA[12]="bo"

BPM_CRATE_12_CPU_HOSTNAME="IA-12RaBPM-CO-IOCSrv"
BPM_CRATE_12_MCH_HOSTNAME="IA-12RaBPM-CO-CrateCtrl"

# Crate 13 FPGA bitstreams definitions
BPM_CRATE_13_FPGA[1]="timing"
BPM_CRATE_13_FPGA[2]="fofb"
BPM_CRATE_13_FPGA[3]=""
BPM_CRATE_13_FPGA[4]=""
BPM_CRATE_13_FPGA[5]="pbpm"
BPM_CRATE_13_FPGA[6]=""
BPM_CRATE_13_FPGA[7]="sr"
BPM_CRATE_13_FPGA[8]="sr"
BPM_CRATE_13_FPGA[9]="sr"
BPM_CRATE_13_FPGA[10]="sr"
BPM_CRATE_13_FPGA[11]="bo"
BPM_CRATE_13_FPGA[12]=""

BPM_CRATE_13_CPU_HOSTNAME="IA-13RaBPM-CO-IOCSrv"
BPM_CRATE_13_MCH_HOSTNAME="IA-13RaBPM-CO-CrateCtrl"

# Crate 14 FPGA bitstreams definitions
BPM_CRATE_14_FPGA[1]="timing"
BPM_CRATE_14_FPGA[2]="fofb"
BPM_CRATE_14_FPGA[3]=""
BPM_CRATE_14_FPGA[4]="pbpm"
BPM_CRATE_14_FPGA[5]=""
BPM_CRATE_14_FPGA[6]=""
BPM_CRATE_14_FPGA[7]="sr"
BPM_CRATE_14_FPGA[8]="sr"
BPM_CRATE_14_FPGA[9]="sr"
BPM_CRATE_14_FPGA[10]="sr"
BPM_CRATE_14_FPGA[11]="bo"
BPM_CRATE_14_FPGA[12]="bo"

BPM_CRATE_14_CPU_HOSTNAME="IA-14RaBPM-CO-IOCSrv"
BPM_CRATE_14_MCH_HOSTNAME="IA-14RaBPM-CO-CrateCtrl"

# Crate 15 FPGA bitstreams definitions
BPM_CRATE_15_FPGA[1]="timing"
BPM_CRATE_15_FPGA[2]="fofb"
BPM_CRATE_15_FPGA[3]=""
BPM_CRATE_15_FPGA[4]=""
BPM_CRATE_15_FPGA[5]=""
BPM_CRATE_15_FPGA[6]=""
BPM_CRATE_15_FPGA[7]="sr"
BPM_CRATE_15_FPGA[8]="sr"
BPM_CRATE_15_FPGA[9]="sr"
BPM_CRATE_15_FPGA[10]="sr"
BPM_CRATE_15_FPGA[11]="bo"
BPM_CRATE_15_FPGA[12]=""

BPM_CRATE_15_CPU_HOSTNAME="IA-15RaBPM-CO-IOCSrv"
BPM_CRATE_15_MCH_HOSTNAME="IA-15RaBPM-CO-CrateCtrl"

# Crate 16 FPGA bitstreams definitions
BPM_CRATE_16_FPGA[1]="timing"
BPM_CRATE_16_FPGA[2]="fofb"
BPM_CRATE_16_FPGA[3]=""
BPM_CRATE_16_FPGA[4]=""
BPM_CRATE_16_FPGA[5]=""
BPM_CRATE_16_FPGA[6]=""
BPM_CRATE_16_FPGA[7]="sr"
BPM_CRATE_16_FPGA[8]="sr"
BPM_CRATE_16_FPGA[9]="sr"
BPM_CRATE_16_FPGA[10]="sr"
BPM_CRATE_16_FPGA[11]="bo"
BPM_CRATE_16_FPGA[12]="bo"

BPM_CRATE_16_CPU_HOSTNAME="IA-16RaBPM-CO-IOCSrv"
BPM_CRATE_16_MCH_HOSTNAME="IA-16RaBPM-CO-CrateCtrl"

# Crate 17 FPGA bitstreams definitions
BPM_CRATE_17_FPGA[1]="timing"
BPM_CRATE_17_FPGA[2]="fofb"
BPM_CRATE_17_FPGA[3]=""
BPM_CRATE_17_FPGA[4]=""
BPM_CRATE_17_FPGA[5]=""
BPM_CRATE_17_FPGA[6]=""
BPM_CRATE_17_FPGA[7]="sr"
BPM_CRATE_17_FPGA[8]="sr"
BPM_CRATE_17_FPGA[9]="sr"
BPM_CRATE_17_FPGA[10]="sr"
BPM_CRATE_17_FPGA[11]="bo"
BPM_CRATE_17_FPGA[12]=""

BPM_CRATE_17_CPU_HOSTNAME="IA-17RaBPM-CO-IOCSrv"
BPM_CRATE_17_MCH_HOSTNAME="IA-17RaBPM-CO-CrateCtrl"

# Crate 18 FPGA bitstreams definitions
BPM_CRATE_18_FPGA[1]="timing"
BPM_CRATE_18_FPGA[2]="fofb"
BPM_CRATE_18_FPGA[3]=""
BPM_CRATE_18_FPGA[4]=""
BPM_CRATE_18_FPGA[5]=""
BPM_CRATE_18_FPGA[6]=""
BPM_CRATE_18_FPGA[7]="sr"
BPM_CRATE_18_FPGA[8]="sr"
BPM_CRATE_18_FPGA[9]="sr"
BPM_CRATE_18_FPGA[10]="sr"
BPM_CRATE_18_FPGA[11]="bo"
BPM_CRATE_18_FPGA[12]="bo"

BPM_CRATE_18_CPU_HOSTNAME="IA-18RaBPM-CO-IOCSrv"
BPM_CRATE_18_MCH_HOSTNAME="IA-18RaBPM-CO-CrateCtrl"

# Crate 19 FPGA bitstreams definitions
BPM_CRATE_19_FPGA[1]="timing"
BPM_CRATE_19_FPGA[2]="fofb"
BPM_CRATE_19_FPGA[3]=""
BPM_CRATE_19_FPGA[4]=""
BPM_CRATE_19_FPGA[5]=""
BPM_CRATE_19_FPGA[6]=""
BPM_CRATE_19_FPGA[7]="sr"
BPM_CRATE_19_FPGA[8]="sr"
BPM_CRATE_19_FPGA[9]="sr"
BPM_CRATE_19_FPGA[10]="sr"
BPM_CRATE_19_FPGA[11]="bo"
BPM_CRATE_19_FPGA[12]=""

BPM_CRATE_19_CPU_HOSTNAME="IA-19RaBPM-CO-IOCSrv"
BPM_CRATE_19_MCH_HOSTNAME="IA-19RaBPM-CO-CrateCtrl"

# Crate 20 FPGA bitstreams definitions
BPM_CRATE_20_FPGA[1]="timing"
BPM_CRATE_20_FPGA[2]="fofb"
BPM_CRATE_20_FPGA[3]=""
BPM_CRATE_20_FPGA[4]=""
BPM_CRATE_20_FPGA[5]=""
BPM_CRATE_20_FPGA[6]=""
BPM_CRATE_20_FPGA[7]="sr"
BPM_CRATE_20_FPGA[8]="sr"
BPM_CRATE_20_FPGA[9]="sr"
BPM_CRATE_20_FPGA[10]="sr"
BPM_CRATE_20_FPGA[11]="bo"
BPM_CRATE_20_FPGA[12]="bo"

BPM_CRATE_20_CPU_HOSTNAME="IA-20RaBPM-CO-IOCSrv"
BPM_CRATE_20_MCH_HOSTNAME="IA-20RaBPM-CO-CrateCtrl"

# Crate 21 (20 TL) FPGA bitstreams definitions
BPM_CRATE_21_FPGA[1]="timing"
BPM_CRATE_21_FPGA[2]=""
BPM_CRATE_21_FPGA[3]=""
BPM_CRATE_21_FPGA[4]=""
BPM_CRATE_21_FPGA[5]=""
BPM_CRATE_21_FPGA[6]="sr"
BPM_CRATE_21_FPGA[7]="sr"
BPM_CRATE_21_FPGA[8]="sr"
BPM_CRATE_21_FPGA[9]="sr"
BPM_CRATE_21_FPGA[10]="sr"
BPM_CRATE_21_FPGA[11]="sr"
BPM_CRATE_21_FPGA[12]=""

BPM_CRATE_21_CPU_HOSTNAME="IA-20RaBPMTL-CO-IOCSrv"
BPM_CRATE_21_MCH_HOSTNAME="IA-20RaBPMTL-CO-CrateCtrl"

# Crate 22 (Homolog) FPGA bitstreams definitions
BPM_CRATE_22_FPGA[1]="timing"
BPM_CRATE_22_FPGA[2]="fofb"
BPM_CRATE_22_FPGA[3]=""
BPM_CRATE_22_FPGA[4]="pbpm"
BPM_CRATE_22_FPGA[5]="pbpm"
BPM_CRATE_22_FPGA[6]=""
BPM_CRATE_22_FPGA[7]="sr"
BPM_CRATE_22_FPGA[8]="sr"
BPM_CRATE_22_FPGA[9]="sr"
BPM_CRATE_22_FPGA[10]="sr"
BPM_CRATE_22_FPGA[11]="bo"
BPM_CRATE_22_FPGA[12]="bo"

BPM_CRATE_22_CPU_HOSTNAME="DE-22RaBPM-CO-IOCSrv"
BPM_CRATE_22_MCH_HOSTNAME="DE-22RaBPM-CO-CrateCtrl"

# Crate 23 (Tests) FPGA bitstreams definitions
BPM_CRATE_23_FPGA[1]=""
BPM_CRATE_23_FPGA[2]=""
BPM_CRATE_23_FPGA[3]=""
BPM_CRATE_23_FPGA[4]=""
BPM_CRATE_23_FPGA[5]=""
BPM_CRATE_23_FPGA[6]=""
BPM_CRATE_23_FPGA[7]=""
BPM_CRATE_23_FPGA[8]=""
BPM_CRATE_23_FPGA[9]=""
BPM_CRATE_23_FPGA[10]=""
BPM_CRATE_23_FPGA[11]=""
BPM_CRATE_23_FPGA[12]=""

BPM_CRATE_23_CPU_HOSTNAME="DE-23RaBPM-CO-IOCSrv"
BPM_CRATE_23_MCH_HOSTNAME="DE-23RaBPM-CO-CrateCtrl"


# Crate 24 (Tests) FPGA bitstreams definitions
BPM_CRATE_24_FPGA[1]=""
BPM_CRATE_24_FPGA[2]=""
BPM_CRATE_24_FPGA[3]=""
BPM_CRATE_24_FPGA[4]=""
BPM_CRATE_24_FPGA[5]=""
BPM_CRATE_24_FPGA[6]=""
BPM_CRATE_24_FPGA[7]=""
BPM_CRATE_24_FPGA[8]=""
BPM_CRATE_24_FPGA[9]=""
BPM_CRATE_24_FPGA[10]=""
BPM_CRATE_24_FPGA[11]=""
BPM_CRATE_24_FPGA[12]=""

BPM_CRATE_24_CPU_HOSTNAME="DE-24RaBPM-CO-IOCSrv"
BPM_CRATE_24_MCH_HOSTNAME="DE-24RaBPM-CO-CrateCtrl"


# Crate 25 (Tests) FPGA bitstreams definitions
BPM_CRATE_25_FPGA[1]=""
BPM_CRATE_25_FPGA[2]=""
BPM_CRATE_25_FPGA[3]=""
BPM_CRATE_25_FPGA[4]=""
BPM_CRATE_25_FPGA[5]=""
BPM_CRATE_25_FPGA[6]=""
BPM_CRATE_25_FPGA[7]=""
BPM_CRATE_25_FPGA[8]=""
BPM_CRATE_25_FPGA[9]=""
BPM_CRATE_25_FPGA[10]=""
BPM_CRATE_25_FPGA[11]=""
BPM_CRATE_25_FPGA[12]=""

BPM_CRATE_25_CPU_HOSTNAME="DE-25RaBPM-CO-IOCSrv"
BPM_CRATE_25_MCH_HOSTNAME="DE-25RaBPM-CO-CrateCtrl"
