#!/usr/bin/env bash

declare -a BPM_CRATE_1_FPGA
declare -a BPM_CRATE_2_FPGA
declare -a BPM_CRATE_3_FPGA
declare -a BPM_CRATE_4_FPGA
declare -a BPM_CRATE_5_FPGA
declare -a BPM_CRATE_6_FPGA
declare -a BPM_CRATE_7_FPGA
declare -a BPM_CRATE_8_FPGA
declare -a BPM_CRATE_9_FPGA
declare -a BPM_CRATE_10_FPGA
declare -a BPM_CRATE_11_FPGA
declare -a BPM_CRATE_12_FPGA
declare -a BPM_CRATE_13_FPGA
declare -a BPM_CRATE_14_FPGA
declare -a BPM_CRATE_15_FPGA
declare -a BPM_CRATE_16_FPGA
declare -a BPM_CRATE_17_FPGA
declare -a BPM_CRATE_18_FPGA
declare -a BPM_CRATE_19_FPGA
declare -a BPM_CRATE_20_FPGA
declare -a BPM_CRATE_21_FPGA
declare -a BPM_CRATE_22_FPGA

# Crate 1 FPGA bitstreams definitions
BPM_CRATE_1_FPGA[1]="timing"
BPM_CRATE_1_FPGA[2]=""
BPM_CRATE_1_FPGA[3]=""
BPM_CRATE_1_FPGA[4]=""
BPM_CRATE_1_FPGA[5]=""
BPM_CRATE_1_FPGA[6]=""
BPM_CRATE_1_FPGA[7]="sr"
BPM_CRATE_1_FPGA[8]="sr"
BPM_CRATE_1_FPGA[9]="sr"
BPM_CRATE_1_FPGA[10]="sr"
BPM_CRATE_1_FPGA[11]="bo"
BPM_CRATE_1_FPGA[12]=""

# Crate 2 FPGA bitstreams definitions
BPM_CRATE_2_FPGA[1]="timing"
BPM_CRATE_2_FPGA[2]=""
BPM_CRATE_2_FPGA[3]=""
BPM_CRATE_2_FPGA[4]=""
BPM_CRATE_2_FPGA[5]=""
BPM_CRATE_2_FPGA[6]=""
BPM_CRATE_2_FPGA[7]="sr"
BPM_CRATE_2_FPGA[8]="sr"
BPM_CRATE_2_FPGA[9]="sr"
BPM_CRATE_2_FPGA[10]="sr"
BPM_CRATE_2_FPGA[11]="bo"
BPM_CRATE_2_FPGA[12]="bo"

# Crate 3 FPGA bitstreams definitions
BPM_CRATE_3_FPGA[1]="timing"
BPM_CRATE_3_FPGA[2]=""
BPM_CRATE_3_FPGA[3]=""
BPM_CRATE_3_FPGA[4]=""
BPM_CRATE_3_FPGA[5]=""
BPM_CRATE_3_FPGA[6]=""
BPM_CRATE_3_FPGA[7]="sr"
BPM_CRATE_3_FPGA[8]="sr"
BPM_CRATE_3_FPGA[9]="sr"
BPM_CRATE_3_FPGA[10]="sr"
BPM_CRATE_3_FPGA[11]="bo"
BPM_CRATE_3_FPGA[12]=""

# Crate 4 FPGA bitstreams definitions
BPM_CRATE_4_FPGA[1]="timing"
BPM_CRATE_4_FPGA[2]=""
BPM_CRATE_4_FPGA[3]=""
BPM_CRATE_4_FPGA[4]=""
BPM_CRATE_4_FPGA[5]=""
BPM_CRATE_4_FPGA[6]=""
BPM_CRATE_4_FPGA[7]="sr"
BPM_CRATE_4_FPGA[8]="sr"
BPM_CRATE_4_FPGA[9]="sr"
BPM_CRATE_4_FPGA[10]="sr"
BPM_CRATE_4_FPGA[11]="bo"
BPM_CRATE_4_FPGA[12]="bo"

# Crate 5 FPGA bitstreams definitions
BPM_CRATE_5_FPGA[1]="timing"
BPM_CRATE_5_FPGA[2]=""
BPM_CRATE_5_FPGA[3]=""
BPM_CRATE_5_FPGA[4]=""
BPM_CRATE_5_FPGA[5]=""
BPM_CRATE_5_FPGA[6]=""
BPM_CRATE_5_FPGA[7]="sr"
BPM_CRATE_5_FPGA[8]="sr"
BPM_CRATE_5_FPGA[9]="sr"
BPM_CRATE_5_FPGA[10]="sr"
BPM_CRATE_5_FPGA[11]="bo"
BPM_CRATE_5_FPGA[12]=""

# Crate 6 FPGA bitstreams definitions
BPM_CRATE_6_FPGA[1]="timing"
BPM_CRATE_6_FPGA[2]=""
BPM_CRATE_6_FPGA[3]=""
BPM_CRATE_6_FPGA[4]="pbpm"
BPM_CRATE_6_FPGA[5]=""
BPM_CRATE_6_FPGA[6]="sr"
BPM_CRATE_6_FPGA[7]="sr"
BPM_CRATE_6_FPGA[8]="sr"
BPM_CRATE_6_FPGA[9]="sr"
BPM_CRATE_6_FPGA[10]="sr"
BPM_CRATE_6_FPGA[11]="bo"
BPM_CRATE_6_FPGA[12]="bo"

# Crate 7 FPGA bitstreams definitions
BPM_CRATE_7_FPGA[1]="timing"
BPM_CRATE_7_FPGA[2]=""
BPM_CRATE_7_FPGA[3]=""
BPM_CRATE_7_FPGA[4]="pbpm"
BPM_CRATE_7_FPGA[5]=""
BPM_CRATE_7_FPGA[6]="sr"
BPM_CRATE_7_FPGA[7]="sr"
BPM_CRATE_7_FPGA[8]="sr"
BPM_CRATE_7_FPGA[9]="sr"
BPM_CRATE_7_FPGA[10]="sr"
BPM_CRATE_7_FPGA[11]="bo"
BPM_CRATE_7_FPGA[12]=""

# Crate 8 FPGA bitstreams definitions
BPM_CRATE_8_FPGA[1]="timing"
BPM_CRATE_8_FPGA[2]=""
BPM_CRATE_8_FPGA[3]=""
BPM_CRATE_8_FPGA[4]="pbpm"
BPM_CRATE_8_FPGA[5]=""
BPM_CRATE_8_FPGA[6]="sr"
BPM_CRATE_8_FPGA[7]="sr"
BPM_CRATE_8_FPGA[8]="sr"
BPM_CRATE_8_FPGA[9]="sr"
BPM_CRATE_8_FPGA[10]="sr"
BPM_CRATE_8_FPGA[11]="bo"
BPM_CRATE_8_FPGA[12]="bo"

# Crate 9 FPGA bitstreams definitions
BPM_CRATE_9_FPGA[1]="timing"
BPM_CRATE_9_FPGA[2]=""
BPM_CRATE_9_FPGA[3]=""
BPM_CRATE_9_FPGA[4]="pbpm"
BPM_CRATE_9_FPGA[5]=""
BPM_CRATE_9_FPGA[6]="sr"
BPM_CRATE_9_FPGA[7]="sr"
BPM_CRATE_9_FPGA[8]="sr"
BPM_CRATE_9_FPGA[9]="sr"
BPM_CRATE_9_FPGA[10]="sr"
BPM_CRATE_9_FPGA[11]="bo"
BPM_CRATE_9_FPGA[12]=""

# Crate 10 FPGA bitstreams definitions
BPM_CRATE_10_FPGA[1]="timing"
BPM_CRATE_10_FPGA[2]=""
BPM_CRATE_10_FPGA[3]=""
BPM_CRATE_10_FPGA[4]=""
BPM_CRATE_10_FPGA[5]="pbpm"
BPM_CRATE_10_FPGA[6]=""
BPM_CRATE_10_FPGA[7]="sr"
BPM_CRATE_10_FPGA[8]="sr"
BPM_CRATE_10_FPGA[9]="sr"
BPM_CRATE_10_FPGA[10]="sr"
BPM_CRATE_10_FPGA[11]="bo"
BPM_CRATE_10_FPGA[12]="bo"

# Crate 11 FPGA bitstreams definitions
BPM_CRATE_11_FPGA[1]="timing"
BPM_CRATE_11_FPGA[2]=""
BPM_CRATE_11_FPGA[3]=""
BPM_CRATE_11_FPGA[4]="pbpm"
BPM_CRATE_11_FPGA[5]=""
BPM_CRATE_11_FPGA[6]="sr"
BPM_CRATE_11_FPGA[7]="sr"
BPM_CRATE_11_FPGA[8]="sr"
BPM_CRATE_11_FPGA[9]="sr"
BPM_CRATE_11_FPGA[10]="sr"
BPM_CRATE_11_FPGA[11]="bo"
BPM_CRATE_11_FPGA[12]=""

# Crate 12 FPGA bitstreams definitions
BPM_CRATE_12_FPGA[1]="timing"
BPM_CRATE_12_FPGA[2]=""
BPM_CRATE_12_FPGA[3]=""
BPM_CRATE_12_FPGA[4]="pbpm"
BPM_CRATE_12_FPGA[5]="pbpm"
BPM_CRATE_12_FPGA[6]="sr"
BPM_CRATE_12_FPGA[7]="sr"
BPM_CRATE_12_FPGA[8]="sr"
BPM_CRATE_12_FPGA[9]="sr"
BPM_CRATE_12_FPGA[10]="sr"
BPM_CRATE_12_FPGA[11]="bo"
BPM_CRATE_12_FPGA[12]="bo"

# Crate 13 FPGA bitstreams definitions
BPM_CRATE_13_FPGA[1]="timing"
BPM_CRATE_13_FPGA[2]=""
BPM_CRATE_13_FPGA[3]=""
BPM_CRATE_13_FPGA[4]=""
BPM_CRATE_13_FPGA[5]="pbpm"
BPM_CRATE_13_FPGA[6]="sr"
BPM_CRATE_13_FPGA[7]="sr"
BPM_CRATE_13_FPGA[8]="sr"
BPM_CRATE_13_FPGA[9]="sr"
BPM_CRATE_13_FPGA[10]="sr"
BPM_CRATE_13_FPGA[11]="bo"
BPM_CRATE_13_FPGA[12]=""

# Crate 14 FPGA bitstreams definitions
BPM_CRATE_14_FPGA[1]="timing"
BPM_CRATE_14_FPGA[2]=""
BPM_CRATE_14_FPGA[3]=""
BPM_CRATE_14_FPGA[4]="pbpm"
BPM_CRATE_14_FPGA[5]="pbpm"
BPM_CRATE_14_FPGA[6]="sr"
BPM_CRATE_14_FPGA[7]="sr"
BPM_CRATE_14_FPGA[8]="sr"
BPM_CRATE_14_FPGA[9]="sr"
BPM_CRATE_14_FPGA[10]="sr"
BPM_CRATE_14_FPGA[11]="bo"
BPM_CRATE_14_FPGA[12]="bo"

# Crate 15 FPGA bitstreams definitions
BPM_CRATE_15_FPGA[1]="timing"
BPM_CRATE_15_FPGA[2]=""
BPM_CRATE_15_FPGA[3]=""
BPM_CRATE_15_FPGA[4]="pbpm"
BPM_CRATE_15_FPGA[5]=""
BPM_CRATE_15_FPGA[6]="sr"
BPM_CRATE_15_FPGA[7]="sr"
BPM_CRATE_15_FPGA[8]="sr"
BPM_CRATE_15_FPGA[9]="sr"
BPM_CRATE_15_FPGA[10]="sr"
BPM_CRATE_15_FPGA[11]="bo"
BPM_CRATE_15_FPGA[12]=""

# Crate 16 FPGA bitstreams definitions
BPM_CRATE_16_FPGA[1]="timing"
BPM_CRATE_16_FPGA[2]=""
BPM_CRATE_16_FPGA[3]=""
BPM_CRATE_16_FPGA[4]=""
BPM_CRATE_16_FPGA[5]=""
BPM_CRATE_16_FPGA[6]=""
BPM_CRATE_16_FPGA[7]="sr"
BPM_CRATE_16_FPGA[8]="sr"
BPM_CRATE_16_FPGA[9]="sr"
BPM_CRATE_16_FPGA[10]="sr"
BPM_CRATE_16_FPGA[11]="bo"
BPM_CRATE_16_FPGA[12]="bo"

# Crate 17 FPGA bitstreams definitions
BPM_CRATE_17_FPGA[1]="timing"
BPM_CRATE_17_FPGA[2]=""
BPM_CRATE_17_FPGA[3]=""
BPM_CRATE_17_FPGA[4]=""
BPM_CRATE_17_FPGA[5]=""
BPM_CRATE_17_FPGA[6]=""
BPM_CRATE_17_FPGA[7]="sr"
BPM_CRATE_17_FPGA[8]="sr"
BPM_CRATE_17_FPGA[9]="sr"
BPM_CRATE_17_FPGA[10]="sr"
BPM_CRATE_17_FPGA[11]="bo"
BPM_CRATE_17_FPGA[12]=""

# Crate 18 FPGA bitstreams definitions
BPM_CRATE_18_FPGA[1]="timing"
BPM_CRATE_18_FPGA[2]=""
BPM_CRATE_18_FPGA[3]=""
BPM_CRATE_18_FPGA[4]=""
BPM_CRATE_18_FPGA[5]=""
BPM_CRATE_18_FPGA[6]=""
BPM_CRATE_18_FPGA[7]="sr"
BPM_CRATE_18_FPGA[8]="sr"
BPM_CRATE_18_FPGA[9]="sr"
BPM_CRATE_18_FPGA[10]="sr"
BPM_CRATE_18_FPGA[11]="bo"
BPM_CRATE_18_FPGA[12]="bo"

# Crate 19 FPGA bitstreams definitions
BPM_CRATE_19_FPGA[1]="timing"
BPM_CRATE_19_FPGA[2]=""
BPM_CRATE_19_FPGA[3]=""
BPM_CRATE_19_FPGA[4]=""
BPM_CRATE_19_FPGA[5]=""
BPM_CRATE_19_FPGA[6]=""
BPM_CRATE_19_FPGA[7]="sr"
BPM_CRATE_19_FPGA[8]="sr"
BPM_CRATE_19_FPGA[9]="sr"
BPM_CRATE_19_FPGA[10]="sr"
BPM_CRATE_19_FPGA[11]="bo"
BPM_CRATE_19_FPGA[12]=""

# Crate 20 FPGA bitstreams definitions
BPM_CRATE_20_FPGA[1]="timing"
BPM_CRATE_20_FPGA[2]=""
BPM_CRATE_20_FPGA[3]=""
BPM_CRATE_20_FPGA[4]=""
BPM_CRATE_20_FPGA[5]=""
BPM_CRATE_20_FPGA[6]=""
BPM_CRATE_20_FPGA[7]="sr"
BPM_CRATE_20_FPGA[8]="sr"
BPM_CRATE_20_FPGA[9]="sr"
BPM_CRATE_20_FPGA[10]="sr"
BPM_CRATE_20_FPGA[11]="bo"
BPM_CRATE_20_FPGA[12]="bo"

# Crate 21 FPGA bitstreams definitions
BPM_CRATE_21_FPGA[1]="timing"
BPM_CRATE_21_FPGA[2]=""
BPM_CRATE_21_FPGA[3]=""
BPM_CRATE_21_FPGA[4]=""
BPM_CRATE_21_FPGA[5]=""
BPM_CRATE_21_FPGA[6]="sr"
BPM_CRATE_21_FPGA[7]="sr"
BPM_CRATE_21_FPGA[8]="sr"
BPM_CRATE_21_FPGA[9]="sr"
BPM_CRATE_21_FPGA[10]="sr"
BPM_CRATE_21_FPGA[11]="sr"
BPM_CRATE_21_FPGA[12]=""

# Crate 22 FPGA bitstreams definitions
BPM_CRATE_22_FPGA[1]="timing"
BPM_CRATE_22_FPGA[2]=""
BPM_CRATE_22_FPGA[3]=""
BPM_CRATE_22_FPGA[4]="pbpm"
BPM_CRATE_22_FPGA[5]="pbpm"
BPM_CRATE_22_FPGA[6]="sr"
BPM_CRATE_22_FPGA[7]="sr"
BPM_CRATE_22_FPGA[8]="sr"
BPM_CRATE_22_FPGA[9]="sr"
BPM_CRATE_22_FPGA[10]="sr"
BPM_CRATE_22_FPGA[11]="bo"
BPM_CRATE_22_FPGA[12]="bo"
